title: It's a beautiful day
author: Linda Maria K J
theme: minima
email: mlindakj@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Butterfly Butterfly Butterfly fly away
# social links
twitter_username: lindamaria # DO NOT include the @ character, or else the build will fail!
github_username:  LindaMariaKJ # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
